### ISSUE TITLE
TypeError on import: "TypeError: <class 'webknossos.dataset.properties.LayerProperties'> has no usable non-default attributes" 

### ISSUE THREAD

**Issue by MariusCausemann** [scalableminds/webknossos-libs#1180]
Hi,
I'm trying to import webknossos in a python script, but a TypeError is thrown on import.

## Expected Behavior
webknossos should be imported without an error.

## Current Behavior
Currently, the following error is thrown:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/__init__.py", line 27, in <module>
    from .administration import *
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/administration/__init__.py", line 2, in <module>
    from .project import Project
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/administration/project.py", line 6, in <module>
    from ..client.api_client.models import ApiProject
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/client/__init__.py", line 2, in <module>
    from ._upload_dataset import LayerToLink
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/client/_upload_dataset.py", line 12, in <module>
    from ..dataset import Dataset, Layer, RemoteDataset
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/dataset/__init__.py", line 14, in <module>
    from .dataset import Dataset, RemoteDataset
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/dataset/dataset.py", line 43, in <module>
    from ._utils import pims_images
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/dataset/_utils/pims_images.py", line 31, in <module>
    from ..mag_view import MagView
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/dataset/mag_view.py", line 25, in <module>
    from .properties import MagViewProperties
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/webknossos/dataset/properties.py", line 330, in <module>
    make_dict_structure_fn(
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/gen/__init__.py", line 772, in make_dict_structure_fn
    return make_dict_structure_fn_from_attrs(
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/gen/__init__.py", line 406, in make_dict_structure_fn_from_attrs
    handler = find_structure_handler(
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/gen/_shared.py", line 52, in find_structure_handler
    handler = c.get_structure_hook(type, cache_result=False)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/converters.py", line 562, in get_structure_hook
    else self._structure_func.dispatch_without_caching(type)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/dispatch.py", line 134, in dispatch_without_caching
    res = self._function_dispatch.dispatch(typ)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/dispatch.py", line 75, in dispatch
    return handler(typ, self._converter)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/cols.py", line 118, in list_structure_factory
    handler = converter.get_structure_hook(elem_type)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/converters.py", line 560, in get_structure_hook
    self._structure_func.dispatch(type)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/dispatch.py", line 134, in dispatch_without_caching
    res = self._function_dispatch.dispatch(typ)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/dispatch.py", line 76, in dispatch
    return handler(typ)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/converters.py", line 636, in _gen_attrs_union_structure
    dis_fn = self._get_dis_func(cl, use_literals=use_literals)
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/converters.py", line 962, in _get_dis_func
    return create_default_dis_func(
  File "/home/mariusca/yes/envs/wktest/lib/python3.10/site-packages/cattrs/disambiguators.py", line 159, in create_default_dis_func
    raise TypeError(f"{cl} has no usable non-default attributes")
TypeError: <class 'webknossos.dataset.properties.LayerProperties'> has no usable non-default attributes
```

## Steps to Reproduce the bug
The bug can be reproduced with:

1. install webknossos with pip
2. Run `python3 -c "import webknossos"`

## Your Environment for bug
I'm on ubuntu linux with python3.10 with webknossos 0.15.1.

**Comment by hotzenklotz** [comment]
Thanks for letting us know. 

@markbader Can you please have a look at this.

**Comment by winnubstj** [comment]
Just ran into this myself and seems to be related to recent upgrade of cattrs to 24.1.0. Setting the version to 23.2.3 works for me

**Comment by MariusCausemann** [comment]
Thanks @winnubstj ! Fixing cattrs to 23.2.3 solved the problem for me.

**Comment by CamachoDejay** [comment]
pip install cattrs==23.2.3 also solved my problem
