### ISSUE TITLE
nearest interpolation does not work

### ISSUE THREAD

**Issue by erjel** [scalableminds/webknossos-libs#551]
Hi,

for me the nearest interpolation does not work in the downsampling.

Test code to create the dataset:
```python
import numpy as np
from webknossos import Dataset

data = np.random.randint(0, 255, (1024, 1024, 1024), dtype=np.uint8)

Dataset('sample_wkw', scale=(256.0, 256.0, 35.0))\
    .get_or_add_layer('segmentation', 'segmentation', dtype_per_layer=np.uint8, largest_segment_id=int(255))\
    .add_mag(1)\
    .write(data)
```
and the cli run:
```bash
poetry run python -m wkcuber.downsampling --layer_name segmentation -i nearest -j 10 ./debug
``` 
produces an error:
```
2022-01-06 10:28:49,644 INFO Using pool of 1 workers.
Downsampling layer segmentation from Mag 1 to Mag 1-1-2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0:00:00 | -:--:--2022-01-06 10:28:49,907 DEBUG the selected filtering strategy does not support anisotropic downsampling. Selecting 1 as uniform downsampling factor
Downsampling layer segmentation from Mag 1 to Mag 1-1-2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0:00:02 | -:--:--2022-01-06 10:28:51,877 DEBUG the selected filtering strategy does not support anisotropic downsampling. Selecting 1 as uniform downsampling factor
Downsampling layer segmentation from Mag 1 to Mag 1-1-2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0:00:04 | -:--:--2022-01-06 10:28:53,978 ERROR Downsampling of target BoundingBox(offset=Vec3Int(0,0,0), size=Vec3Int(1024,1024,512)) failed with could not broadcast input array from shape (256,256,512) into shape (256,256,256)
2022-01-06 10:28:53,981 ERROR A future crashed with an exception: could not broadcast input array from shape (256,256,512) into shape (256,256,256). Future: <Future at 0x7fd7a8964370 state=finished raised ValueError>
Downsampling layer segmentation from Mag 1 to Mag 1-1-2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0:00:04 | -:--:--
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "${HOME}/usr/miniconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "${HOME}/src/webknossos-libs/webknossos/webknossos/dataset/downsampling_utils.py", line 346, in downsample_cube_job
    raise exc
  File "${HOME}/src/webknossos-libs/webknossos/webknossos/dataset/downsampling_utils.py", line 330, in downsample_cube_job
    file_buffer[
ValueError: could not broadcast input array from shape (256,256,512) into shape (256,256,256)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "${HOME}/usr/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "${HOME}/usr/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "${HOME}/src/webknossos-libs/wkcuber/wkcuber/downsampling.py", line 154, in <module>
    downsample_mags(
  File "${HOME}/src/webknossos-libs/wkcuber/wkcuber/downsampling.py", line 125, in downsample_mags
    Dataset.open(path).get_layer(layer_name).downsample(
  File "${HOME}/src/webknossos-libs/webknossos/webknossos/dataset/layer.py", line 600, in downsample
    self.downsample_mag(
  File "${HOME}/src/webknossos-libs/webknossos/webknossos/dataset/layer.py", line 693, in downsample_mag
    source_view.for_zipped_chunks(
  File "${HOME}/src/webknossos-libs/webknossos/webknossos/dataset/view.py", line 485, in for_zipped_chunks
    wait_and_ensure_success(
  File "${HOME}/src/webknossos-libs/webknossos/webknossos/utils.py", line 103, in wait_and_ensure_success
    results.append(fut.result())
  File "${HOME}/usr/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "${HOME}/usr/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: could not broadcast input array from shape (256,256,512) into shape (256,256,256)
```

**Comment by leowe** [comment]
I found the problem:
```
DEBUG the selected filtering strategy does not support anisotropic downsampling. Selecting 1 as uniform downsampling factor.
```
Since `nearest` interpolation is implemented by the `linear_filter_3d` function (opposed to the `non_linear_filter_3d` used for e.g. `mean` interpolation), it doesn't support anisotropic downsampling, so the function *assumes* that the user is using isotropic downsampling and prints the debug message. 

One thing we can do is to do an assert so that it fails more meaningfully if it is used for anisotropic downsampling, but I have not read up enough on the downsampling methods to judge whether it's generally possible to implement `nearest` interpolation for anisotropic downsampling. We should probably also update the relevant docs to more clearly reflect on which mode is possible for which configuration.
@jstriebel what do you think?

**Comment by jstriebel** [comment]
Thanks for looking into this! I agree with you, we probably should do both:
1. Adding an assertion and docs, so this error is explained better to the user.
2. Remove this assertion and add anisotropic nearest interpolation.

Let's do the first step now, and follow-up with actually fixing it afterwards.
