### ISSUE TITLE
AssertionError: Can only compare wk.Graph to another wk.Graph

### ISSUE THREAD

**Issue by amotta** [scalableminds/webknossos-libs#591]
Yagmur and I have just installed the `webknossos` package (version 0.9.4) from PyPI and tried to load an NML file (written by our MATLAB code). This resulted in the following assertion error:

```
>>> skel = webknossos.Skeleton.load("/home/amotta/Desktop/agglomerate-1327233.nml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amotta/.miniconda3/envs/blah/lib/python3.8/site-packages/webknossos/skeleton/skeleton.py", line 65, in load
    return nml_to_skeleton(wknml.parse_nml(file_handle))
  File "/home/amotta/.miniconda3/envs/blah/lib/python3.8/site-packages/webknossos/skeleton/nml/to_skeleton.py", line 38, in to_skeleton
    new_graph = skeleton.add_graph(
  File "/home/amotta/.miniconda3/envs/blah/lib/python3.8/site-packages/webknossos/skeleton/group.py", line 57, in add_graph
    self._children.add(new_graph)
  File "/home/amotta/.miniconda3/envs/blah/lib/python3.8/site-packages/webknossos/skeleton/graph.py", line 147, in __eq__
    assert isinstance(
AssertionError: Can only compare wk.Graph to another wk.Graph.
```

Are we doing anything wrong or is this a bug in the webknossos library?

**Comment by hotzenklotz** [comment]
@amotta Please share the NML file for investigation.

**Comment by jstriebel** [comment]
This seems to be a bug in the library, I have an idea what might go wrong (group-children is a set consisting of graphs and groups, comparison between a graph and a group leads to the above error). I'll try to reproduce it and add a fix soon.

**Comment by amotta** [comment]
https://datashare.mpcdf.mpg.de/s/93xy1hy7sAqJfxH
