### ISSUE TITLE
Support Skeleton only annotations in the Annotation API

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos-libs#665]
It seems like the current version of the Annotation API does not support skeleton-only annotations.

### Steps to reproduce
The following code crashes in the last line.
```python
with webknossos_context(WEBKNOSSOS_URL, user_auth_token):
    annotation = Annotation.download(
        f"{WEBKNOSSOS_URL}/annotations/{annotation_type}/{annotation_id}"
    )
    nml = annotation.skeleton
```
The error is:
```
File is not a zip file
Traceback (most recent call last):
  File "/Users/Shared/ScalableMinds/webknossos-worker/webknossos_worker/work_polling.py", line 110, in run_job
    return_value = command_fn(run_id, run_logger, **job_kwargs)  # type: ignore
  File "/Users/Shared/ScalableMinds/webknossos-worker/webknossos_worker/tasks.py", line 632, in apply_merger_mode
    nml = annotation.skeleton
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/site-packages/webknossos/annotation/annotation.py", line 73, in skeleton
    return Skeleton.load(self._nml_file)
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/site-packages/webknossos/annotation/annotation.py", line 67, in _nml_file
    nml_files = [i for i in self._filelist if i.endswith(".nml")]
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/site-packages/webknossos/annotation/annotation.py", line 63, in _filelist
    return [i.filename for i in self._zipfile.filelist]
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/site-packages/webknossos/annotation/annotation.py", line 59, in _zipfile
    return ZipFile(self.file)
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/Users/michael/.conda/envs/webknossos-worker/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

### Expected Behaviour

The annotation API should not fail once trying to access the skeleton of a skeleton only tracing. It should simply return the nml as it does for hybrid tracings. Instead it should fail if one tries to access the volumetracing data of a skeleton only tracing.

**Comment by MichaelBuessemeyer** [comment]
Jep it looks like this bug does not exist anymore in version 0.9.13
