### ISSUE TITLE
cluster_tools logging error

### ISSUE THREAD

**Issue by elhuhdron** [scalableminds/webknossos-libs#711]
It seems they have removed the `file=` keyword in `logging.debug()`. I tried with python 3.8.13 and 3.8.12, and then gave up figuring out when it was removed and instead just commented 3 occurrences of `file=` in [`cluster_executor.py`](https://github.com/scalableminds/webknossos-libs/blob/master/cluster_tools/cluster_tools/schedulers/cluster_executor.py). This fix worked and my cubing job then finished without any errors.

```
2022-04-26 09:16:38,134 ERROR exception calling callback for <Future at 0x7fdf35449ee0 state=finished returned int>
Traceback (most recent call last):
  File "/gpfs/soma_fs/home/watkins/miniconda3/envs/wkw/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/gpfs/soma_fs/home/watkins/miniconda3/envs/wkw/lib/python3.8/site-packages/cluster_tools/schedulers/cluster_executor.py", line 424, in register_jobs
    logging.debug(
  File "/gpfs/soma_fs/home/watkins/miniconda3/envs/wkw/lib/python3.8/logging/__init__.py", line 2092, in debug
    root.debug(msg, *args, **kwargs)
  File "/gpfs/soma_fs/home/watkins/miniconda3/envs/wkw/lib/python3.8/logging/__init__.py", line 1434, in debug
    self._log(DEBUG, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'file'
```

**Comment by philippotto** [comment]
> I tried with python 3.8.13 and 3.8.12, and then gave up figuring out when it was removed and instead just commented 3 occurrences of file= in [cluster_executor.py](https://github.com/scalableminds/webknossos-libs/blob/master/cluster_tools/cluster_tools/schedulers/cluster_executor.py)

Thanks for the report and for looking into this :+1: Just fyi: I also had a look and came to this conclusion:

> The parameter was never really used for the logging call anyway (earlier versions used `print` here where it made sense). Newer python versions complain about this invalid parameter.

(from https://github.com/scalableminds/webknossos-libs/pull/735)
