### ISSUE TITLE
wkcuber fails if spaces in tiff file name

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-libs#717]
Trying to cube a multi-page tiff file with 
`python -m wkcuber --scale 1,2,3 --name myDataset --max_mag 32 /input/path /output/path`
(in the directory is a single tiff file with spaces in the file name)

getting

```
2022-04-25 12:02:43,047 INFO Converting image stack
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/wkcuber/__main__.py", line 114, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/wkcuber/__main__.py", line 110, in main
    cube_with_args(args)
  File "/usr/local/lib/python3.8/site-packages/wkcuber/__main__.py", line 80, in cube_with_args
    auto_detect_and_run_conversion(args)
  File "/usr/local/lib/python3.8/site-packages/wkcuber/converter.py", line 550, in main
    should_write_metadata = matching_converters[0].convert_input(args)
  File "/usr/local/lib/python3.8/site-packages/wkcuber/converter.py", line 388, in convert_input
    if not all_files_of_same_type(
  File "/usr/local/lib/python3.8/site-packages/wkcuber/converter.py", line 85, in all_files_of_same_type
    _, ext = path.splitext(input_files[0])
IndexError: list index out of range
```

Removing the spaces in the filename on disk helps.

**Comment by markbader** [comment]
This does not seem to be an issue anymore. I tested the conversion of a .tif file with spaces in filename and it works now. As the method that created the Error and the wkcuber do not exist anymore, I will close this issue.
