### ISSUE TITLE
download function crash

### ISSUE THREAD

**Issue by boergens** [scalableminds/webknossos-libs#779]
```
import webknossos as wk
with wk.client.context.webknossos_context(token="SUPERSECRET",url='https://webknossos.myurl.org'):
	wk.Dataset.download('txm_a1_gt01',
            path='./',
            layers=['color'],
            webknossos_url='https://webknossos.myurl.org',
            bbox=wk.geometry.bounding_box.BoundingBox.from_tuple6([0,0,0,512,512,200]),
            mags=[wk.geometry.mag.Mag(1)])


```

```
(env) boergens@DESKTOP-4L0H931:~/webknossos$ pip list
Package            Version
------------------ ---------
aiohttp            3.8.1
aiosignal          1.2.0
anyio              3.5.0
asciitree          0.3.3
async-timeout      4.0.2
attrs              21.4.0
boltons            21.0.0
cachetools         5.2.0
cattrs             1.7.1
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.1.0
cloudpickle        2.0.0
cluster-tools      0.10.10
colorama           0.4.4
commonmark         0.9.1
cycler             0.11.0
fasteners          0.17.3
fonttools          4.29.1
frozenlist         1.3.0
fsspec             2022.7.1
google-auth        2.9.1
h11                0.12.0
httpcore           0.13.7
httpx              0.18.2
idna               3.3
imageio            2.16.0
kiwisolver         1.3.2
kubernetes         23.6.0
loxun              2.0
matplotlib         3.5.1
multidict          6.0.2
networkx           2.6.3
numcodecs          0.9.1
numpy              1.22.2
oauthlib           3.2.0
packaging          21.3
Pillow             9.0.1
pip                20.0.2
pkg-resources      0.0.0
psutil             5.9.0
pyasn1             0.4.8
pyasn1-modules     0.2.8
pycparser          2.21
Pygments           2.11.2
pyparsing          3.0.7
python-dateutil    2.8.2
python-dotenv      0.19.2
PyWavelets         1.2.0
PyYAML             6.0
requests           2.28.1
requests-oauthlib  1.3.1
rfc3986            1.5.0
rich               10.16.2
rsa                4.9
scikit-image       0.18.3
scipy              1.8.0
setuptools         44.0.0
six                1.16.0
sniffio            1.2.0
tifffile           2022.2.9
typing-extensions  4.3.0
universal-pathlib  0.0.19
urllib3            1.26.11
webknossos         0.10.10
websocket-client   1.3.3
wknml              1.1.2
wkw                1.1.17
yarl               1.7.2
zarr               2.12.0
zipp               3.8.1
```

```Traceback (most recent call last):
  File "forgw.py", line 5, in <module>
    wk.Dataset.download('txm_a1_gt01',
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/dataset/dataset.py", line 440, in download
    return download_dataset(
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_download_dataset.py", line 39, in download_dataset
    dataset_info_response = dataset_info.sync_detailed(
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_generated/api/default/dataset_info.py", line 73, in sync_detailed
    return _build_response(response=response)
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_generated/api/default/dataset_info.py", line 51, in _build_response
    parsed=_parse_response(response=response),
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_generated/api/default/dataset_info.py", line 40, in _parse_response
    response_200 = DatasetInfoResponse200.from_dict(response.json())
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_generated/models/dataset_info_response_200.py", line 152, in from_dict
    jobs_enabled = d.pop("jobsEnabled")
KeyError: 'jobsEnabled'
```

**Comment by fm3** [comment]
Hi and thanks for your report! Would you mind sharing the webKnossos server version as reported by `https://webknossos.myurl.org/api/buildinfo`? The `jobsEnabled` field that the python client expects in the server’s response was added in webKnossos server release [21.08.0](https://github.com/scalableminds/webknossos/releases/tag/21.08.0). 

We are planning to improve the compatibility between webknossos server and webknossos-libs versions (tracked in issue https://github.com/scalableminds/webknossos/issues/5840 ), but for now, it is recommended to use the latest releases for both.

**Comment by boergens** [comment]
Ok, that explains it. This one is on 21.05.1 (which is weird in itself, it was installed a few months ago using Docker and this tutorial https://docs.webknossos.org/webknossos/installation.html ). But I guess that's an issue for another day :-) Thank you for your help

![image](https://user-images.githubusercontent.com/1429753/182161273-5329ff7b-82e3-404f-8f62-fe1e8f335806.png)

**Comment by boergens** [comment]
Ok, while doing this bug report I had upgraded to the latest webknossos-lib version (0.10.10) to make sure that that's not the problem. Unfortunately that broke my other download code:

```
import webknossos as wk
for idx in range(50):
        wk.Dataset.download('mntb-C57-18m-001_segmentation_v1_mapping25',
                                path='/mnt/d/qq'+str(idx)+'/',
                                layers=['segmentation'],
                                webknossos_url='https://webknossos.org',
                                organization_name='b2275d664e4c2a96',
                                bbox=wk.geometry.bounding_box.BoundingBox.from_tuple6([0,idx*1024,0,8371,1024,1520]),
                                mags=[wk.geometry.mag.Mag(1)])
```

I poked around a bit and found that `organization_name` has changed to `organization_id` at 0.9.13
https://github.com/scalableminds/webknossos-libs/pull/639
So I guess before the upgrade I was on a smaller than 0.9.13 version.
So I changed `organization_name` to `organization_id` in the above code.
When I execute that I get the following error:
```
Traceback (most recent call last):
  File "downloader.py", line 3, in <module>
    wk.Dataset.download('mntb-C57-18m-001_segmentation_v1_mapping25',
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/dataset/dataset.py", line 440, in download
    return download_dataset(
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_download_dataset.py", line 39, in download_dataset
    dataset_info_response = dataset_info.sync_detailed(
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_generated/api/default/dataset_info.py", line 73, in sync_detailed
    return _build_response(response=response)
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_generated/api/default/dataset_info.py", line 51, in _build_response
    parsed=_parse_response(response=response),
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_generated/api/default/dataset_info.py", line 40, in _parse_response
    response_200 = DatasetInfoResponse200.from_dict(response.json())
  File "/home/boergens/webknossos/env/lib/python3.8/site-packages/webknossos/client/_generated/models/dataset_info_response_200.py", line 146, in from_dict
    publication = d.pop("publication")
KeyError: 'publication'
```

Any idea what that's about? This is the official wK webserver with the latest released version of webknossos-libs

**Comment by fm3** [comment]
Thanks again for your report! This is a bug on our side. We will fix this on the server side tomorrow. Sorry about the inconvenience! We will also prioritize guarding the client against such breaking changes.

**Comment by fm3** [comment]
I just deployed the fix on the webknossos.org server, dataset download via python works for me now. Please try again!
