### ISSUE TITLE
Not sure how to debug AttributeError: _cached_array

### ISSUE THREAD

**Issue by azatian** [scalableminds/webknossos-libs#780]
I have a tiff file that I was trying to convert to a wkw file for upload
My command was 
python3 -m wkcuber --voxel_size 11.24,11.24,25 --name dcv_example ./source_two ./target

In source_two I have my .tiff file

The output I get, which I can't seem to pass is here:
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/wkcuber/__main__.py", line 115, in <module>
    main()
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/wkcuber/__main__.py", line 111, in main
    cube_with_args(args)
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/wkcuber/__main__.py", line 80, in cube_with_args
    auto_detect_and_run_conversion(args)
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/wkcuber/converter.py", line 559, in main
    should_write_metadata = matching_converters[0].convert_input(args)
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/wkcuber/converter.py", line 441, in convert_input
    executor_args,
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/wkcuber/cubing.py", line 386, in cubing
    chunk_size=chunk_size,
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/webknossos/dataset/layer.py", line 494, in get_or_add_mag
    compress=compression_mode or False,
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/webknossos/dataset/layer.py", line 394, in add_mag
    create=True,
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/webknossos/dataset/mag_view.py", line 70, in __init__
    BaseArray.get_class(array_info.data_format).create(self_path, array_info)
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/webknossos/dataset/_array.py", line 202, in create
    else wkw.Header.BLOCK_TYPE_RAW
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/wkw/wkw.py", line 97, in __init__
    assert voxel_type in self.VALID_VOXEL_TYPES
AssertionError
Exception ignored in: <function View.__del__ at 0x7febd1465f80>
Traceback (most recent call last):
  File "/data/personal_folders/yazatian/pyenv37/lib/python3.7/site-packages/webknossos/dataset/view.py", line 963, in __del__
    del self._cached_array
AttributeError: _cached_array

Would really appreciate some help here!

Thanks,
Yervand

**Comment by azatian** [comment]
Hi Jonathan,
Thank you so much for your reply and guidance! Yes, the dtype of my tiff is float16. I am going to do a conversion and see if that gets me anywhere.

**Comment by azatian** [comment]
I converted the nparray that eventually became the tiff to uint8. I was able to convert using wkcuber now and upload to our WK instance! Thanks again

**Comment by jstriebel** [comment]
Great that this helped you. Also, the error message should now be much better using the new python `webknossos` package `v0.10.11`.
