### ISSUE TITLE
`wkcuber` docker image crashes on startup

### ISSUE THREAD

**Issue by kiler129** [scalableminds/webknossos-libs#871]
## Context
- Affected library: wkcuber

The Docker image built from CI doesn't work properly when attempting to run the combined pipeline CLI tool. It crashes with an error pointing to a module not being present in the image.

## Expected Behavior
All commands should run in the Docker container. I see that the CI only tests `wkcuber.cubing`. I don't believe this should be the case as this is only a small part of the image. Is there a reason why CI only executes cubing and not the whole `wkcuber`?

## Current Behavior
```
# docker run --rm scalableminds/webknossos-cuber wkcuber --help
Traceback (most recent call last):
  File "/app/wkcuber/_internal/versioning.py", line 23, in get_available_version
    return get_package_version()
  File "/app/wkcuber/_internal/versioning.py", line 10, in get_package_version
    from wkcuber.version import __version__
ModuleNotFoundError: No module named 'wkcuber.version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/wkcuber/__main__.py", line 117, in <module>
    main()
  File "/app/wkcuber/__main__.py", line 111, in main
    args = create_parser().parse_args()
  File "/app/wkcuber/__main__.py", line 64, in create_parser
    "--version", action="version", version=f"wkcuber {get_available_version()}"
  File "/app/wkcuber/_internal/versioning.py", line 25, in get_available_version
    return get_git_version()
  File "/app/wkcuber/_internal/versioning.py", line 4, in get_git_version
    git_hash = git.Repo(search_parent_directories=True).head.object.hexsha
  File "/usr/local/lib/python3.8/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/usr/local/lib/python3.8/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

## Steps to Reproduce the bug
Run `docker run --rm scalableminds/webknossos-cuber wkcuber`

## Your Environment for bug
- Operating System and version:
```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

# docker --version
Docker version 23.0.1, build a5ee5b1
```
- Version of webKnossos-libs (Release or Commit): pulled tag `latest`; as of the time of writing it is 0.12.0

---

*p.s. also, the GH action for new issues is broken: https://github.com/scalableminds/webknossos-libs/actions/runs/4197674316/jobs/7280302752*

**Comment by normanrz** [comment]
This should now work with the newly released Docker images:
`docker run --rm scalableminds/webknossos-cuber:v0.12.2 wkcuber --help`

Thanks for reporting!
